name: dart_random_logo
description: SVD based sampling algorithm for generating fractal-like logos.
version: 1.0.0

environment:
  sdk: ^3.4.4

# Add regular dependencies here.
dependencies:
  image: ^4.2.0
  vector_math: ^2.1.4

dev_dependencies:
  lints: ^3.0.0
  test: ^1.24.0
